name: Deployement
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run lint
      - name: Check Tests
        run: npm run test
      - name:  Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."