name: Deployement
on: [push, workflow_dispatch]
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run lint
  test-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
  deploy:
    needs: [lint-check, test-check]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Check Tests
        run: npm run test
      - name:  Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."